Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -32,6 +32,24 @@ jobs:
           else
             echo "sha=${{ github.event.after || github.head_ref || github.event.pull_request.head.sha  }}" >> "${GITHUB_OUTPUT}"
           fi
+
+      # From https://github.com/Tiryoh/gha-jobid-action
+      - name: Parse job_id
+        id: jobid
+        shell: bash
+        run: |
+          GITHUB_API="/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs"
+          JOBINFO="$(curl --get -Ss -H "Authorization: Bearer ${INPUT_GITHUB_TOKEN}" -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" "${{ github.api_url }}${GITHUB_API}?per_page=100")"
+          echo "${JOBINFO}"
+          echo "${JOBINFO}" | grep "Resource not accessible by integration" &&  exit 1
+          eval "$(echo ${JOBINFO} | jq -r --arg job_name "${INPUT_JOB_NAME}" '.jobs | map(select(.name == $job_name)) | .[0] | @sh "job_id=\(.id) html_url=\(.html_url)"')"
+          echo ${job_id} | grep "null" > /dev/null && echo "parse error, job_id is ${job_id}. job name might be wrong. See https://github.com/Tiryoh/gha-jobid-action" && exit 1
+          echo "job_id=${job_id}" >> $GITHUB_OUTPUT
+          echo "html_url=${html_url}" >> $GITHUB_OUTPUT
+      - id: job-url
+        run: |
+          echo "url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ steps.jobid.outputs.job_id }}" >> "${GITHUB_OUTPUT}"
+
       - uses: actions/github-script@v7
         with:
           script: |
@@ -41,7 +59,7 @@ jobs:
               sha: "${{ steps.head.outputs.sha }}",
               state: "pending",
               context: context.workflow,
-              target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+              target_url: "${{ steps.job-url.outputs.url }}",
             });
 
       - id: start
@@ -68,7 +86,7 @@ jobs:
               sha: "${{ steps.head.outputs.sha }}",
               state: "${{ job.status }}",
               context: context.workflow,
-              target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+              target_url: "${{ steps.job-url.outputs.url }}",
               description: "${{ steps.result-message.outputs.message }}",
             });
       - uses: actions/github-script@v7
@@ -81,6 +99,6 @@ jobs:
               sha: "${{ steps.head.outputs.sha }}",
               state: "error",
               context: context.workflow,
-              target_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
+              target_url: "${{ steps.job-url.outputs.url }}",
               description: "${{ steps.result-message.outputs.message }} ${{ job.status }}",
             });
